services:
  strapi:
    container_name: strapi-usharani
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
#      - ./package-lock.json:/opt/package-lock.json
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1338:1337'
    networks:
      - strapi

  strapiAdminer:
    container_name: strapiAdminerUsha
    image: adminer
    restart: unless-stopped
    ports:
      - '9091:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=${DATABASE_HOST}  # AWS RDS endpoint
    networks:
      - strapi

networks:
  strapi:
    name: Strapi
    driver: bridge
